[package]
name = "rust-redis-server"
version = "0.1.0"
edition = "2021"
license = "MIT"
author = "Paxon Qiao <qiaopengjun0@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
